# Site settings
title: Resume
author:
  name: Vedang 
  #email: your-email@domain.com
#description: "Great site about Jekyll on GH-Pages."
logo: Vedang.png
show_downloads: true
# Build settings
remote_theme: jekyll/minima

